<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>AWSDeploymentAssistant</RootNamespace>
    <AssemblyName>AWSDeploymentAssistant</AssemblyName>
    <Configurations>Debug;Release;Deploy</Configurations>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="4.0.3.15" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.18.7" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="log4net" Version="3.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Solution Items\Properties\GlobalAssemblyInfo.cs" Link="Properties\GlobalAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Readme.md" Link="Readme.md" CopyToOutputDirectory="Always" />
    <None Include="..\LICENSE" Link="LICENSE" />
    <None Include="plugins\Readme.md" CopyToOutputDirectory="Always" />
    <Content Include="..\License.CommandLine.txt" Link="License.CommandLine.txt" CopyToOutputDirectory="Always" />
    <Content Include="..\License.log4net.txt" Link="License.log4net.txt" CopyToOutputDirectory="Always" />
    <Content Include="..\License.Newtonsoft.Json.txt" Link="License.Newtonsoft.Json.txt" CopyToOutputDirectory="Always" />
    <Content Include="..\License.YamlDotNet.txt" Link="License.YamlDotNet.txt" CopyToOutputDirectory="Always" />
    <Content Include="..\Notice.txt" Link="Notice.txt" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>