<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <RootNamespace>CodeDeployPlugin</RootNamespace>
    <AssemblyName>CodeDeployPlugin</AssemblyName>
    <Configurations>Debug;Release;Deploy</Configurations>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\AWSDeploymentAssistant\bin\Debug\$(TargetFramework)\plugins\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\AWSDeploymentAssistant\bin\Release\$(TargetFramework)\plugins\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AWSDeploymentAssistant\AWSDeploymentAssistant.csproj" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Solution Items\Properties\GlobalAssemblyInfo.cs" Link="Properties\GlobalAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\defaultBeforeInstall.ps1" />
    <EmbeddedResource Include="Resources\defaultApplicationStart.ps1" />
    <EmbeddedResource Include="Resources\defaultApplicationStop.ps1" />
  </ItemGroup>
</Project>